version: '3'
services:
  app:
    image: slazy/studentapp
    ports:
      - "8080:8080" # Map port 8080 on the host to port 8080 in the container
    environment:
      - NODE_ENV=production
